---
{% raw %}
- hosts: localhost
  connection: local
  vars:
    molecule_file: "{{ lookup('env','MOLECULE_FILE') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:
    - name: Destroy molecule instance(s)
      vagrant:
        instance_name: "{{ item.name | instance_with_scenario_name(molecule_yml.scenario.name) }}"
        platform_box: ubuntu/trusty64
        molecule_file: "{{ molecule_file }}"
        state: destroy
      with_items: "{{ molecule_yml.platforms }}"
{%- endraw -%}
